### PR TITLE
Do not break minification

### PR DESCRIPTION
**Pull request by marob**
Better code conventions in order not to break minification (missing semicolons can have edge effects)

### CODE REVIEW

**Comment by alexei** [comment]
Can have or does have?

**Comment by marob** [comment]
I've encountered problems in my project and I've been forced to use the packaged minified version instead of the sources (that would have been minified by my own grunt tasks).
The minification process doesn't fail per se, but the resulting minified and concatenated file is buggy (the next script follows sprintf.js that doesn't end by a ";").

**Comment by alexei** [comment]
sprintf.js correctly ends with a ;

**Comment by marob** [comment]
Sorry, I'm using angular-sprintf.js which does NOT end with a ";"

**Comment by alexei** [comment]
That one, indeed, is at fault.

I will open an issue for that. If you want to fix it, be my guest.

I will not, however, merge this PR. It only adds semicolons which were, in fact, left out on purpose.

Regarding the use of double quotes: that's how I currently use JS. I might change it though in the future to align it with my Python habits i.e. double quotes for natural language text, single quotes for other strings e.g. msg['invalid_email'] = "Please enter a valid email address."

**Pull request closed without merging**
