### PR TITLE
Leave original placeholder if attribute is not present in passed object

### PR DESCRIPTION
**Pull request by vdiez**
When using named arguments, value in output for the field is currently replaced to 'undefined'. This change leaves the original placeholder instead of changing its value.

### CODE REVIEW

**Comment by vdiez** [comment]
any option to have this PR merged?

**Comment by alexei** [comment]
Sorry - what is this about?

**Comment by vdiez** [comment]
Imagine this use case where placeholders to replace are spread among different objects: 
 
```
let command = 'cp %(source)s %(target)s' 
let params1 = {source: '/mnt/file1'} 
let params2 = {target: '/mnt/file2'}

```
With this change I can chain them like that:
```
let command = sprintf(command, params1)
let command = sprintf(command, params2)
```

With current version I cannot, because after the first call, the placeholder `%(target)s` will be replaced by `undefined`.

**Comment by alexei** [comment]
This has been asked and discussed before, and I stand by my opinion that one should validate their data.

Besides, use cases such as this one could be implemented using `Proxy` objects where they e.g. return `%(property)s` for each missing property.

**Comment by vdiez** [comment]
In my case data is validated, but there is a workflow where each parameter/-s is provided on a different step and by different modules. Of course, my example was way simpler than real use case.

My opinion is that this PR keeps the result more stateless and in any case i doubt having undefined in the final string is preferable and cleaner when the property is not found. 

I understand the subjectivity of this. Feel free to close the PR

**Comment by alexei** [comment]
Does it work if `params1`, `params2` are `Proxy` objects?

**Comment by vdiez** [comment]
ok, i was doing a long explanation of why not until I understood what you meant. 

so yes, Proxy object should work. I'll do that then :)

cheers

**Pull request closed without merging**
