### PR TITLE
Add dependencies-badges

### PR DESCRIPTION
**Pull request by RABEHAJA-STEVENS**

### CODE REVIEW

**Comment by alexei** [comment]
Can you please move them in line with the title? See for example https://github.com/angular/angular.js

**Comment by RABEHAJA-STEVENS** [comment]
I have changed it next the title as what you requested. There, it is please.

**Comment by alexei** [comment]
Looks good, thanks

**Comment by RABEHAJA-STEVENS** [comment]
You are welcome!!!

**Pull request merged**
