### PR TITLE
Add arguments for computed values

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by alexei** [comment]
That looks like a bad idea

**Comment by bertho-zero** [comment]
Why ? this information is useful here.

**Comment by alexei** [comment]
That's leaking private details to the outside world

**Comment by bertho-zero** [comment]
I do not understand how it is a data leak to the outside world ? it is the same signature as `Array.prototype.map` or `Array.prototype.forEach` and `arg` is not user input, it is fully controlled by the developer.

How can I know what data is displayed and in what way if I am not the value, its index and the type of the token ?

**Comment by alexei** [comment]
It's leaking the tree

**Comment by bertho-zero** [comment]
I have removed the last argument although I still do not understand the risk.

**Comment by bertho-zero** [comment]
@alexei Can you detail what risk it "protects" from? Do you forbid yourself from using Array.map/filter/reduce because it leaks information in exactly the same way?

How do you know what to display without having the index and the type of token? I have to parse the string myself to find the tokens and their positions? it is not very efficient.

**Pull request closed without merging**
