### PR TITLE
Optimizations for modern browsers

### PR DESCRIPTION
**Pull request by nazar-pc**
Each commit contains pretty distinct change and can be picked separately from the rest.
The only breaking change for older browsers is that `String.prototype.repeat` should be present.

These changes allow ~10% reduction of gzipped library size after Google Closure Compiler minifier. I've tried to replace uglifyjs with closure-compiler-js, but it seems to be broken (at least gulp version of it), awfully documented and I wan't able to get it working in advanced mode even though [Closure Compiler Service](https://closure-compiler.appspot.com) works perfectly with these sources.

### CODE REVIEW

**Comment by alexei** [comment]
Excellent!

**Comment by MaxBittker** [comment]
hey, I think this should have been a major semver bump. This totally changed the API and caused us a small bit of pain. I appreciate the work you do to improve this library but respecting semver allows us to actually benefit from these changes instead of pinning to an old version forever. 

http://semver.org/

https://github.com/alexei/sprintf.js/pull/139/commits/96f8581d61af6aae320adcccde3bb0fff9bf8dd4

**Comment by nazar-pc** [comment]
@MaxBittker what kind of API are you talking about? Public API should be exactly the same as before.

**Comment by MaxBittker** [comment]
we consume the library like this:  https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/locale.jsx#L45

i see now that parse was probably intended to be an internal method, but it wasn't apparent to us :/

**Comment by nazar-pc** [comment]
It was an implementation detail used for internal purposes and was never declared as public interface, so using it was on your own risk.
Why can't you call `sprintf()` directly? Can't figure it out from the code you've linked, looks like you need some kind of callback for each placeholder match in formatting string, how does it work?

**Comment by MaxBittker** [comment]
we were doing something janky to format to react nodes for localization instead of to a string, which in retrospect was probably not well advised. I retract my complaint about the versioning. Thanks for improving the library!

**Comment by alexei** [comment]
@MaxBittker I'm not sure I understand what that piece of code you linked to is [supposed to be] doing

**Pull request merged**
