### PR TITLE
Feature eslint

### PR DESCRIPTION
**Pull request by msimerson**
this is PR #127, rebased and addressing comments in the PR.

closes #127

### CODE REVIEW

**Comment by alexei** [comment]
Thank you!

Let's wait a couple of days for @MeriemKhelifi to have the chance to update his PR.

Btw, removing the quotes flag also means not fixing the quotes in the source files. There are a couple of places (in the tests) where I've been inconsistent, but I can fix those myself.

**Comment by msimerson** [comment]
FWIW, I prefer the single quotes. It's become a convention in JS and _when in Rome, do as the Romans_. So a few years back I opted to swim with the current and switched to single quotes by default. But there's also much to be said for programmer discretion and "live and let live," so I don't ever have that rule enabled in enforcing mode in repos. There are [many times when it makes more sense to use double quotes](http://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript?noredirect=1&lq=1). 

PS: Bringing in the `eslint:recommended` is a GREAT default, as is setting up Travis to run your lint & tests automatically every time a PR is created.

**Comment by alexei** [comment]
See https://github.com/alexei/sprintf.js/pull/127#issuecomment-299647793 re quotes. Having a mixed background, I don't agree with all the motions of the JS community.

I don't know what `eslint:recommended` is. I don't do much JS nowadays, only toy projects in my spare time. I saw it's there, I assume it's some sort of a recommended style, I trust it's probably good 🙂

Re Travis, yes, I should probably do that.

**Comment by msimerson** [comment]
`eslint:recommended` is a pragmatic set of "best practices" that it applies automatically. All of the recommended rules are conventions adopted by the community. Based on your comments in #127, I think it's something you'd could support with very little arm twisting. Thats compared to Standard, which is much more opinionated, and has opinions you disagree with.

If you'll go to travis-ci.org and enable it for your repo, someone else might create a PR that makes the changes necessary in this repo. Hint. Hint.

**Comment by ArmorDarks** [comment]
As I've mentioned here https://github.com/alexei/sprintf.js/pull/127#issuecomment-299667200, I strongly recommend to use [Standard](https://github.com/feross/standard) as established community best practice in JS env instead. Stop wasting time on formatting-related decisions, it doesn't help productivity.

**Comment by msimerson** [comment]
> I strongly recommend to use Standard as established community best practice in JS env instead.

We heard you @ArmorDarks . @alexei has already stated he doesn't agree with one of the core requirements of standard. Ease up on the proselytizing please.

**Comment by ArmorDarks** [comment]
Yeap, maybe you're right. I just wanted to ensure that my comment in other related PR wasn't lost.

**Comment by msimerson** [comment]
It's been a couple days. If this PR were merged, and some indication that the repo owner had enabled Travis for this repo, then another PR that enables automatic running of continuous integration tests, complete with lint and style testing, might appear.

**Comment by alexei** [comment]
Yes, I enabled Travis on Sunday just after you've mentioned it

**Pull request merged**
